name: ci build and push docker image to ECR

on:
  push:
   
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 705307574352.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t mediplus:v2 .
          docker tag mediplus:v2 705307574352.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2
          docker push 705307574352.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Check my ssh key
        run: |
           echo "${{ secrets.SSH_KEY }}" > mykey.pem
           chmod 600 mykey.pem
           cat mykey.pem

           ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@13.221.165.24 "docker pull 705307574352.dkr.ecr.us-east-1.amazonaws.com/mediplus:v3"
           ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@13.221.165.24 "docker rm -f mediplus"
           ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@13.221.165.24 "docker run -d --name mediplus -p 80:80 705307574352.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2"

      